import { createElement, Fragment, useMemo, useState } from './mini-react.js'
import {
  AlertTriangle, ArrowRight, BarChart3, Bell, Briefcase, CalendarDays, Check,
  CheckCircle2, ChevronDown, Clock3, CreditCard, DollarSign, Download, Edit, Eye,
  FileBarChart, FileText, Filter, Grid2X2, Image, LayoutDashboard, Lock, LogOut,
  Menu, MessageCircle, MoreHorizontal, Package, Palette, Plus, Receipt, Search,
  Send, Settings, Shield, Sliders, Sparkles, Target, TrendingUp, UserRound, Users,
  Video, Workflow, X, Zap
} from './icons.jsx'
import {
  adminActivity, adminClients, adminDeliverables, adminInvoices, adminPackages,
  adminReports, adminRequests, adminServices, adminTeam, rolePermissions
} from './data/admin-data.js'

const adminNav = [
  { id:'dashboard', label:'Dashboard', icon:LayoutDashboard },
  { id:'clients', label:'Clientes', icon:Users },
  { id:'packages', label:'Paquetes', icon:Package },
  { id:'deliverables', label:'Entregables', icon:Grid2X2, badge:5 },
  { id:'calendar', label:'Calendario', icon:CalendarDays },
  { id:'billing', label:'Facturación', icon:Receipt, badge:2 },
  { id:'requests', label:'Solicitudes', icon:MessageCircle, badge:2 },
  { id:'services', label:'Servicios adicionales', icon:Briefcase },
  { id:'reports', label:'Reportes', icon:FileBarChart },
  { id:'team', label:'Equipo', icon:UserRound },
  { id:'settings', label:'Configuración', icon:Settings },
]

const labels = {
  active:'Activo', paused:'Pausado', expired:'Vencido', paid:'Pagado', pending:'Pendiente', overdue:'Vencido',
  in_progress:'En proceso', internal_review:'Revisión interna', client_review:'Enviado al cliente', changes:'Cambios solicitados',
  approved:'Aprobado', published:'Publicado', cancelled:'Cancelado', new:'Nueva', review:'En revisión', rejected:'Rechazada',
  converted:'Convertida', completed:'Completada', sent:'Enviado', draft:'Borrador', high:'Alta', medium:'Media', low:'Baja'
}

function AdminLogo() {
  return <div className="admin-logo"><span className="logo-mark"><i /><i /><i /></span><span>biem<span>.</span></span><b>ADMIN</b></div>
}

function Badge({ value, type='status' }) {
  return <span className={`admin-badge ${type} ${value}`}><i />{labels[value] || value}</span>
}

function AdminSidebar({ active, setActive, open, setOpen, role, profile, onLogout }) {
  const allowed = rolePermissions[role] || []
  return <aside className={`admin-sidebar ${open ? 'open' : ''}`}><div className="admin-sidebar-head"><AdminLogo /><button className="admin-mobile-close" onClick={() => setOpen(false)}><X size={20} /></button></div><div className="admin-workspace"><div className="admin-workspace-icon">BD</div><div><small>ESPACIO DE TRABAJO</small><strong>Biem Digital</strong></div><ChevronDown size={15} /></div><nav><span>GESTIÓN</span>{adminNav.filter(item => allowed.includes(item.id)).map(item => { const Icon=item.icon; return <button key={item.id} className={active===item.id?'active':''} onClick={() => { setActive(item.id); setOpen(false) }}><Icon size={18}/><b>{item.label}</b>{item.badge && <em>{item.badge}</em>}</button>})}</nav><div className="admin-sidebar-user"><div className="team-avatar">{(profile.full_name || profile.email || 'BI').split(' ').map(part => part[0]).join('').slice(0,2).toUpperCase()}</div><div><strong>{profile.full_name || profile.email}</strong><span>{role}</span></div><button onClick={onLogout} title="Cerrar sesión"><LogOut size={17}/></button></div></aside>
}

function AdminTopbar({ active, setMenuOpen, role, profile }) {
  const title=adminNav.find(item=>item.id===active)?.label || 'Dashboard'
  return <header className="admin-topbar"><button className="admin-menu-button" onClick={() => setMenuOpen(true)}><Menu size={21}/></button><div><span>BIEM DIGITAL <i>/</i></span><strong>{title}</strong></div><div className="admin-top-actions"><div className="global-search"><Search size={16}/><span>Buscar cliente, pieza o factura...</span><kbd>⌘ K</kbd></div><button className="admin-icon-button"><Bell size={18}/><i/></button><div className="role-switch"><div className="team-avatar">{(profile.full_name || profile.email || 'BI').slice(0,2).toUpperCase()}</div><span>{role}</span></div></div></header>
}

function AdminHeading({ eyebrow, title, copy, action }) {
  return <div className="admin-heading"><div><span className="admin-eyebrow">{eyebrow}</span><h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{action}</div>
}

function TableActions({ onView, onEdit }) { return <div className="table-actions"><button onClick={onView}><Eye size={15}/>Ver</button>{onEdit&&<button onClick={onEdit}><Edit size={15}/>Editar</button>}</div> }

function Dashboard({ setActive }) {
  const cards=[
    ['Clientes activos','3','+1 este mes',Users,'green'],['Entregables pendientes','3','2 con prioridad alta',Clock3,'amber'],['Por revisar','1','Revisión interna',Eye,'lilac'],['Aprobados','2','Listos para publicar',CheckCircle2,'blue'],
    ['Facturas pendientes','2','$1,030 por cobrar',Receipt,'coral'],['Solicitudes nuevas','2','Requieren respuesta',MessageCircle,'lilac'],['Próximas renovaciones','3','En los próximos 30 días',CalendarDays,'green'],['Clientes en riesgo','2','Pago o renovación',AlertTriangle,'coral']]
  return <div className="admin-page"><AdminHeading eyebrow="SÁBADO, 6 DE JUNIO" title="Buenos días, Camila" copy="Aquí tienes una vista clara de lo que necesita atención hoy." action={<button className="admin-primary" onClick={()=>setActive('deliverables')}><Plus size={16}/>Nuevo entregable</button>}/><section className="admin-kpi-grid">{cards.map(([label,value,note,Icon,tone])=><article key={label}><div className={`admin-kpi-icon ${tone}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong><p>{note}</p></article>)}</section><section className="admin-dashboard-grid"><div className="admin-panel activity-panel"><div className="admin-panel-head"><div><span className="admin-eyebrow">MOVIMIENTO DEL PORTAL</span><h2>Actividad reciente</h2></div><button>Ver toda</button></div><div className="activity-list">{adminActivity.map(item=><div className="activity-item" key={item.id}><div className={`activity-icon ${item.type}`}>{item.type==='approved'?<Check size={15}/>:item.type==='paid'?<DollarSign size={15}/>:item.type==='changes'?<Edit size={15}/>:item.type==='report'?<BarChart3 size={15}/>:<Sparkles size={15}/>}</div><div><p><strong>{item.client}</strong> {item.text}</p><span>{item.time}</span></div><button><MoreHorizontal size={17}/></button></div>)}</div></div><div className="admin-panel attention-panel"><div className="admin-panel-head"><div><span className="admin-eyebrow">PRIORIDADES</span><h2>Necesita atención</h2></div></div><button className="attention-row" onClick={()=>setActive('billing')}><div className="attention-date overdue">03<span>JUN</span></div><div><strong>Factura vencida</strong><span>Norte Arquitectura · $490</span></div><ArrowRight size={15}/></button><button className="attention-row" onClick={()=>setActive('requests')}><div className="attention-date request">2<span>NUEVAS</span></div><div><strong>Solicitudes sin asignar</strong><span>Alma Studio y Luma Skin</span></div><ArrowRight size={15}/></button><button className="attention-row" onClick={()=>setActive('clients')}><div className="attention-date renewal">10<span>JUN</span></div><div><strong>Renovación vencida</strong><span>Mesa Once · Personalizado</span></div><ArrowRight size={15}/></button><div className="capacity-card"><div><span>CAPACIDAD DEL EQUIPO</span><strong>72%</strong></div><div><i style={{width:'72%'}}/></div><p>34 de 47 entregables asignados</p></div></div></section></div>
}

function Toolbar({ placeholder='Buscar...', filters=[] }) { return <div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder={placeholder}/></div>{filters.map(filter=><button key={filter}><Filter size={14}/>{filter}<ChevronDown size={13}/></button>)}</div> }

function Clients({ onOpen }) {
  return <div className="admin-page"><AdminHeading eyebrow="CARTERA DE CLIENTES" title="Clientes" copy="Gestiona cada cuenta, su servicio y el estado de la relación." action={<button className="admin-primary"><Plus size={16}/>Nuevo cliente</button>}/><Toolbar placeholder="Buscar cliente o marca..." filters={['Estado','Paquete','Responsable']}/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente</th><th>Paquete</th><th>Estado</th><th>Renovación</th><th>Responsable</th><th>Entregables</th><th>Pago</th><th></th></tr></thead><tbody>{adminClients.map(client=><tr key={client.id}><td><div className="client-cell"><div className={`brand-avatar ${client.risk?'risk':''}`}>{client.initials}</div><div><strong>{client.brand}</strong><span>{client.name}</span></div></div></td><td>{client.package}</td><td><Badge value={client.status}/></td><td>{client.renewal}</td><td>{client.owner}</td><td><strong>{client.deliverables}</strong></td><td><Badge value={client.payment}/></td><td><TableActions onView={()=>onOpen(client)} onEdit={()=>onOpen(client)}/></td></tr>)}</tbody></table></div></div>
}

function ClientDetail({ client, onClose }) {
  const tabs=['Información','Paquete','Entregables','Calendario','Reportes','Facturación','Solicitudes','Mensajes internos']; const [tab,setTab]=useState('Información')
  return <div className="admin-drawer-backdrop" onMouseDown={onClose}><aside className="admin-drawer" onMouseDown={e=>e.stopPropagation()}><header><div className="brand-avatar large">{client.initials}</div><div><span className="admin-eyebrow">FICHA DE CLIENTE</span><h2>{client.brand}</h2><p>{client.name} · {client.email}</p></div><button onClick={onClose}><X size={20}/></button></header><div className="drawer-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="drawer-body">{tab==='Información'?<><div className="client-detail-grid"><div><span>ESTADO</span><Badge value={client.status}/></div><div><span>RESPONSABLE</span><strong>{client.owner}</strong></div><div><span>RENOVACIÓN</span><strong>{client.renewal}</strong></div><div><span>ESTADO DE PAGO</span><Badge value={client.payment}/></div></div><section className="drawer-section"><h3>Uso del paquete</h3><div className="drawer-usage"><div><span>{client.deliverables} piezas</span><strong>{client.usage}%</strong></div><div><i style={{width:`${client.usage}%`}}/></div></div></section><InternalMessages/></>:tab==='Paquete'?<PackageSummary name={client.package}/>:<EmptyModule title={tab} copy={`Información de ${tab.toLowerCase()} para ${client.brand}. La estructura está lista para conectarse a la base de datos.`}/>}</div></aside></div>
}

function PackageSummary({ name }) { const pkg=adminPackages.find(item=>item.name===name)||adminPackages[0]; return <section className="drawer-section"><span className="admin-eyebrow">PAQUETE ACTUAL</span><h2>{pkg.name}</h2><p>{pkg.description}</p><div className="package-allowances"><span><b>{pkg.graphics}</b>Piezas</span><span><b>{pkg.reels}</b>Reels</span><span><b>{pkg.stories}</b>Historias</span><span><b>{pkg.carousels}</b>Carruseles</span></div><ul>{pkg.services.map(service=><li key={service}><Check size={14}/>{service}</li>)}</ul></section> }
function EmptyModule({ title, copy }) { return <div className="admin-empty"><FileText size={28}/><h3>{title}</h3><p>{copy}</p><button className="admin-secondary">Agregar información</button></div> }
function InternalMessages(){ return <section className="drawer-section internal-notes"><div className="note-tabs"><button className="active"><Lock size={13}/>Comentario interno</button><button><MessageCircle size={13}/>Mensaje para cliente</button></div><textarea placeholder="Escribe una nota que solo verá el equipo BIEM..."/><div><span><Lock size={12}/>No visible para el cliente</span><button className="admin-primary"><Send size={14}/>Guardar nota</button></div></section> }

function Packages() {
  const [packages,setPackages]=useState(adminPackages)
  return <div className="admin-page"><AdminHeading eyebrow="OFERTA DE LA AGENCIA" title="Paquetes" copy="Configura alcances claros y asígnalos a cada cliente." action={<button className="admin-primary"><Plus size={16}/>Crear paquete</button>}/><div className="package-admin-grid">{packages.map(pkg=><article className={`package-admin-card ${!pkg.active?'disabled':''}`} key={pkg.id}><header><div><Badge value={pkg.active?'active':'paused'}/><h2>{pkg.name}</h2><p>{pkg.description}</p></div><button><MoreHorizontal size={18}/></button></header><div className="package-price"><small>USD</small><strong>{pkg.price?`$${pkg.price}`:'A medida'}</strong>{pkg.price>0&&<span>/ mes</span>}</div><div className="package-counts"><span><b>{pkg.graphics}</b>Gráficas</span><span><b>{pkg.reels}</b>Reels</span><span><b>{pkg.stories}</b>Historias</span><span><b>{pkg.carousels}</b>Carruseles</span></div><ul>{pkg.services.map(service=><li key={service}><Check size={13}/>{service}</li>)}</ul><footer><span>{pkg.clients} cliente{pkg.clients!==1?'s':''} asignado{pkg.clients!==1?'s':''}</span><div><button className="admin-secondary"><Edit size={14}/>Editar</button><button className="admin-toggle" onClick={()=>setPackages(items=>items.map(item=>item.id===pkg.id?{...item,active:!item.active}:item))}><i className={pkg.active?'on':''}/></button></div></footer></article>)}</div></div>
}

function Deliverables({ onOpen }) {
  return <div className="admin-page"><AdminHeading eyebrow="PRODUCCIÓN DE CONTENIDO" title="Entregables" copy="Coordina responsables, fechas y aprobaciones de cada pieza." action={<button className="admin-primary"><Plus size={16}/>Crear entregable</button>}/><Toolbar placeholder="Buscar entregable..." filters={['Cliente','Responsable','Estado','Tipo']}/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Entregable</th><th>Cliente</th><th>Responsable</th><th>Tipo</th><th>Fecha límite</th><th>Estado</th><th>Prioridad</th><th>Actualización</th><th></th></tr></thead><tbody>{adminDeliverables.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.client}</td><td>{item.owner}</td><td>{item.type}</td><td>{item.due}</td><td><Badge value={item.status}/></td><td><Badge value={item.priority} type="priority"/></td><td><span className="muted-cell">{item.updated}</span></td><td><TableActions onView={()=>onOpen(item)} onEdit={()=>onOpen(item)}/></td></tr>)}</tbody></table></div></div>
}

function DeliverableDetail({ item,onClose }) { const [status,setStatus]=useState(item.status); return <div className="admin-drawer-backdrop" onMouseDown={onClose}><aside className="admin-drawer deliverable-drawer" onMouseDown={e=>e.stopPropagation()}><header><div className="admin-file-icon"><Image size={21}/></div><div><span className="admin-eyebrow">{item.client} · {item.type}</span><h2>{item.name}</h2><p>Última actualización {item.updated.toLowerCase()}</p></div><button onClick={onClose}><X size={20}/></button></header><div className="drawer-body"><div className="form-grid"><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}>{['pending','in_progress','internal_review','client_review','changes','approved','published','cancelled'].map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></label><label>Prioridad<select><option>{labels[item.priority]}</option></select></label><label>Responsable<select><option>{item.owner}</option></select></label><label>Fecha límite<input value={item.due}/></label></div><label className="admin-field">Descripción<textarea placeholder="Describe el objetivo y requerimientos de la pieza..."/></label><div className="upload-box"><FileText size={24}/><strong>Archivo o enlace del entregable</strong><p>Arrastra un archivo o pega un enlace de Drive/Figma.</p><button className="admin-secondary">Agregar recurso</button></div><InternalMessages/><div className="workflow-actions"><button className="admin-secondary">Guardar cambios</button><button className="admin-primary" onClick={()=>setStatus('client_review')}>Enviar a revisión <ArrowRight size={15}/></button></div></div></aside></div> }

function AdminCalendar() {
  const days=Array.from({length:35},(_,i)=>i<1||i>30?null:i); const events={6:[adminDeliverables[10]],7:[adminDeliverables[8]],8:[adminDeliverables[0]],9:[adminDeliverables[4]],10:[adminDeliverables[1]],11:[adminDeliverables[6]],12:[adminDeliverables[2]],13:[adminDeliverables[5]],14:[adminDeliverables[9]],16:[adminDeliverables[7]],18:[adminDeliverables[11]]}
  return <div className="admin-page"><AdminHeading eyebrow="VISTA DE PRODUCCIÓN" title="Calendario administrativo" copy="Todos los entregables del equipo organizados por fecha." action={<button className="admin-primary"><Plus size={16}/>Agregar pieza</button>}/><Toolbar filters={['Todos los clientes','Responsable','Estado','Tipo','Mes']}/><div className="admin-calendar"><div className="admin-weekdays">{['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'].map(day=><span key={day}>{day}</span>)}</div><div className="admin-calendar-grid">{days.map((day,index)=><div className={!day?'blank':''} key={index}>{day&&<><b className={day===6?'today':''}>{day}</b>{events[day]?.map(item=><button className={`admin-calendar-event ${item.status}`} key={item.id}><span>{item.client}</span><strong>{item.name}</strong><small>{item.type} · {item.owner.split(' ')[0]}</small></button>)}</>}</div>)}</div></div></div>
}

function Billing() {
  const [invoices,setInvoices]=useState(adminInvoices)
  const markPaid=id=>setInvoices(items=>items.map(item=>item.id===id?{...item,status:'paid'}:item))
  return <div className="admin-page"><AdminHeading eyebrow="CONTROL FINANCIERO" title="Facturación" copy="Seguimiento simple de cobros, renovaciones y comprobantes." action={<button className="admin-primary"><Plus size={16}/>Generar factura</button>}/><div className="billing-alerts"><article className="danger"><AlertTriangle size={19}/><div><strong>2 facturas vencidas</strong><span>$1,590 requieren seguimiento</span></div><ArrowRight size={16}/></article><article><CalendarDays size={19}/><div><strong>3 renovaciones próximas</strong><span>En los próximos 30 días</span></div><ArrowRight size={16}/></article><article><DollarSign size={19}/><div><strong>$2,730 pendiente</strong><span>Por cobrar este período</span></div><ArrowRight size={16}/></article></div><Toolbar placeholder="Buscar factura o cliente..." filters={['Estado','Fecha','Método']}/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Factura</th><th>Cliente</th><th>Paquete</th><th>Monto</th><th>Próxima factura</th><th>Estado</th><th>Método</th><th>Historial</th><th></th></tr></thead><tbody>{invoices.map(item=><tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.client}</td><td>{item.package}</td><td><strong>${item.amount}</strong></td><td>{item.due}</td><td><Badge value={item.status}/></td><td>{item.method}</td><td>{item.history} facturas</td><td><div className="table-actions billing-actions">{item.status!=='paid'&&<button onClick={()=>markPaid(item.id)}><Check size={14}/>Marcar pagado</button>}<button><Send size={14}/>Recordar</button><button><FileText size={14}/>Generar</button></div></td></tr>)}</tbody></table></div></div>
}

function Requests() {
  const [requests,setRequests]=useState(adminRequests); const update=(id,status)=>setRequests(items=>items.map(item=>item.id===id?{...item,status}:item))
  return <div className="admin-page"><AdminHeading eyebrow="SOLICITUDES DESDE EL PORTAL" title="Solicitudes de clientes" copy="Evalúa, asigna y convierte cada necesidad en trabajo accionable."/><Toolbar placeholder="Buscar solicitud..." filters={['Estado','Prioridad','Responsable']}/><div className="request-admin-grid">{requests.map(item=><article className="request-admin-card" key={item.id}><header><div><Badge value={item.status}/><Badge value={item.priority} type="priority"/></div><span>{item.requested}</span></header><span className="admin-eyebrow">{item.client}</span><h3>{item.type}</h3><p>{item.description}</p><div className="request-meta"><span><CalendarDays size={14}/>Deseada: <strong>{item.deadline}</strong></span><span><FileText size={14}/>{item.files} adjunto{item.files!==1?'s':''}</span><span><UserRound size={14}/>{item.owner}</span></div><footer>{item.status==='new'&&<><button className="admin-secondary" onClick={()=>update(item.id,'rejected')}>Rechazar</button><button className="admin-primary" onClick={()=>update(item.id,'approved')}>Aprobar</button></>}{['approved','review'].includes(item.status)&&<button className="admin-primary" onClick={()=>update(item.id,'converted')}><Zap size={14}/>Convertir en entregable</button>}<button className="admin-secondary"><MessageCircle size={14}/>Responder</button></footer></article>)}</div></div>
}

function Services() {
  const [services,setServices]=useState(adminServices)
  return <div className="admin-page"><AdminHeading eyebrow="CATÁLOGO DEL PORTAL" title="Servicios adicionales" copy="Gestiona qué apoyos puede solicitar cada cliente." action={<button className="admin-primary"><Plus size={16}/>Nuevo servicio</button>}/><Toolbar placeholder="Buscar servicio..." filters={['Categoría','Estado']}/><div className="service-admin-grid">{services.map(item=><article key={item.id}><header><div className="service-admin-icon"><Briefcase size={19}/></div><Badge value={item.active?'active':'paused'}/></header><span className="admin-eyebrow">{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><div className="service-admin-meta"><span>Desde<strong>${item.price}</strong></span><span>Entrega estimada<strong>{item.eta}</strong></span></div><footer><button className="admin-secondary"><Edit size={14}/>Editar</button><button className="visibility-button" onClick={()=>setServices(items=>items.map(service=>service.id===item.id?{...service,active:!service.active}:service))}><Eye size={14}/>{item.active?'Ocultar del portal':'Mostrar en portal'}</button></footer></article>)}</div></div>
}

function Reports() {
  return <div className="admin-page"><AdminHeading eyebrow="CLARIDAD PARA EL CLIENTE" title="Reportes mensuales" copy="Construye la historia detrás de las métricas y próximos pasos." action={<button className="admin-primary"><Plus size={16}/>Crear reporte</button>}/><div className="reports-admin-grid">{adminReports.map(report=><article key={report.id}><div className="report-admin-cover"><BarChart3 size={24}/><span>{report.month}</span><Badge value={report.status}/></div><div className="report-admin-body"><span className="admin-eyebrow">{report.client}</span><h3>{report.summary}</h3><div className="report-preview"><span>MÉTRICAS PRINCIPALES</span><strong>{report.metrics}</strong></div><div className="report-actions"><button className="admin-secondary"><Edit size={14}/>Editar</button><button className="admin-secondary"><Download size={14}/>PDF</button>{report.status!=='approved'&&<button className="admin-primary"><Send size={14}/>Enviar</button>}</div></div></article>)}</div></div>
}

function Team() {
  return <div className="admin-page"><AdminHeading eyebrow="EQUIPO INTERNO" title="Equipo y permisos" copy="Gestiona accesos según las responsabilidades de cada persona." action={<button className="admin-primary"><Plus size={16}/>Invitar miembro</button>}/><div className="permissions-note"><Shield size={20}/><div><strong>Permisos por rol activos</strong><p>Admin ve todo · Finanzas solo facturación · Diseño ve piezas asignadas · Estrategia accede a clientes, reportes y calendario.</p></div><button className="admin-secondary"><Sliders size={14}/>Configurar permisos</button></div><div className="team-admin-grid">{adminTeam.map(member=><article key={member.id}><header><div className="team-avatar large">{member.initials}</div><Badge value={member.active?'active':'paused'}/></header><h3>{member.name}</h3><p>{member.email}</p><span className="role-label">{member.role}</span><div><span><b>{member.clients}</b>Clientes</span><span><b>{member.deliverables}</b>Entregables</span></div><footer><button className="admin-secondary"><Edit size={14}/>Editar usuario</button><button><MoreHorizontal size={17}/></button></footer></article>)}</div></div>
}

function SettingsPage() {
  return <div className="admin-page"><AdminHeading eyebrow="PERSONALIZACIÓN Y OPERACIÓN" title="Configuración del portal" copy="Administra la identidad y datos que ven tus clientes." action={<button className="admin-primary"><Check size={16}/>Guardar cambios</button>}/><div className="settings-layout"><nav><button className="active"><Palette size={16}/>Identidad de marca</button><button><CreditCard size={16}/>Datos de pago</button><button><MessageCircle size={16}/>Comunicación</button><button><Shield size={16}/>Seguridad</button></nav><div className="settings-card"><div className="settings-title"><div><span className="admin-eyebrow">IDENTIDAD</span><h2>Marca de la agencia</h2><p>Esta información aparece en el portal de cada cliente.</p></div><div className="settings-logo"><span className="logo-mark"><i/><i/><i/></span></div></div><div className="form-grid"><label>Nombre de la agencia<input value="Biem Digital"/></label><label>Correo de contacto<input value="hola@biemdigital.com"/></label><label>Teléfono<input value="+57 300 000 0000"/></label><label>Sitio web<input value="biemdigital.com"/></label></div><label className="admin-field">Mensaje de bienvenida<textarea>Todo lo que estamos construyendo para tu marca, en un solo lugar.</textarea></label><div className="color-settings"><span>COLORES PRINCIPALES</span><div><label><i style={{background:'#17201d'}}/>Principal<input value="#17201D"/></label><label><i style={{background:'#ef6e55'}}/>Acento<input value="#EF6E55"/></label><label><i style={{background:'#f5f5f1'}}/>Fondo<input value="#F5F5F1"/></label></div></div><label className="admin-field">Texto de confidencialidad<textarea>La información de este portal es confidencial y exclusiva para el cliente.</textarea></label><label className="switch-field"><span><strong>Mostrar “Powered by Biem Digital”</strong><small>Firma visible en el pie del portal del cliente.</small></span><i className="admin-switch on"/></label></div></div></div>
}

export default function AdminApp({ profile, onSignOut }) {
  const [active,setActive]=useState('dashboard')
  const [menuOpen,setMenuOpen]=useState(false)
  const [client,setClient]=useState(null)
  const [deliverable,setDeliverable]=useState(null)
  const role=profile.role
  const allowed=rolePermissions[role]||[]
  const readOnly=role==='viewer'
  if(!allowed.includes(active)) queueMicrotask(()=>setActive(allowed[0]||'dashboard'))
  const pages={dashboard:<Dashboard setActive={setActive}/>,clients:<Clients onOpen={setClient}/>,packages:<Packages/>,deliverables:<Deliverables onOpen={setDeliverable}/>,calendar:<AdminCalendar/>,billing:<Billing/>,requests:<Requests/>,services:<Services/>,reports:<Reports/>,team:<Team/>,settings:<SettingsPage/>}
  return <div className={`admin-shell ${readOnly?'read-only':''}`}><AdminSidebar active={active} setActive={setActive} open={menuOpen} setOpen={setMenuOpen} role={role} profile={profile} onLogout={onSignOut}/>{menuOpen&&<div className="admin-overlay" onClick={()=>setMenuOpen(false)}/>}<main className="admin-main"><AdminTopbar active={active} setMenuOpen={setMenuOpen} role={role} profile={profile}/>{readOnly&&<div className="read-only-banner"><Eye size={14}/>Modo de solo lectura</div>}{pages[active]}</main>{client&&<ClientDetail client={client} onClose={()=>setClient(null)}/>} {deliverable&&<DeliverableDetail item={deliverable} onClose={()=>setDeliverable(null)}/>}</div>
}
