import { createElement, Fragment, useMemo, useState } from './mini-react.js';
import { ArrowLeft, ArrowRight, BarChart3, Bell, CalendarDays, Check, CheckCircle2, ChevronDown, Circle, Clock3, Download, FileBarChart, FileText, Grid2X2, Image, Instagram, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Paperclip, PencilLine, Play, Plus, Send, Sparkles, Target, TrendingUp, UserRound, Users, Video, X, Zap } from './icons.js';
const navItems = [
    { id: 'summary', label: 'Resumen del mes', icon: LayoutDashboard },
    { id: 'deliverables', label: 'Entregables', icon: Grid2X2, badge: 3 },
    { id: 'calendar', label: 'Calendario', icon: CalendarDays },
    { id: 'report', label: 'Reporte mensual', icon: FileBarChart },
    { id: 'messages', label: 'Mensajes', icon: MessageCircle, dot: true },
];
const statusMap = {
    review: { label: 'Por revisar', className: 'review' },
    approved: { label: 'Aprobado', className: 'approved' },
    published: { label: 'Publicado', className: 'published' },
    changes: { label: 'Cambios solicitados', className: 'changes' },
    scheduled: { label: 'Programado', className: 'scheduled' },
};
const initialDeliverables = [
    { id: 1, title: 'Reel · Rutina de mañana', type: 'Reel', date: '08 Jun', status: 'review', color: 'peach', icon: Video, caption: 'Una rutina simple para empezar el día con intención.', tag: 'EDUCATIVO' },
    { id: 2, title: 'Carrusel · 5 mitos del skincare', type: 'Carrusel', date: '10 Jun', status: 'review', color: 'green', icon: Image, caption: 'Desmitificamos lo que tu piel realmente necesita.', tag: 'VALOR' },
    { id: 3, title: 'Historias · Behind the scenes', type: 'Historias', date: '12 Jun', status: 'review', color: 'lilac', icon: Instagram, caption: 'El proceso detrás de cada fórmula.', tag: 'MARCA' },
    { id: 4, title: 'Reel · Ingrediente del mes', type: 'Reel', date: '04 Jun', status: 'approved', color: 'yellow', icon: Play, caption: 'El ingrediente que transforma tu rutina.', tag: 'PRODUCTO' },
    { id: 5, title: 'Post · Manifiesto de marca', type: 'Post', date: '02 Jun', status: 'published', color: 'coral', icon: Image, caption: 'Creemos en una belleza más consciente.', tag: 'MARCA' },
    { id: 6, title: 'Carrusel · Guía de hidratación', type: 'Carrusel', date: '15 Jun', status: 'scheduled', color: 'blue', icon: Image, caption: 'Tu guía definitiva para una piel hidratada.', tag: 'EDUCATIVO' },
];
const calendarEvents = {
    2: [{ title: 'Manifiesto de marca', type: 'Post', status: 'published' }],
    4: [{ title: 'Ingrediente del mes', type: 'Reel', status: 'approved' }],
    6: [{ title: 'Tips rápidos', type: 'Historias', status: 'scheduled' }],
    8: [{ title: 'Rutina de mañana', type: 'Reel', status: 'review', need: 'Necesitamos tu video' }],
    10: [{ title: '5 mitos del skincare', type: 'Carrusel', status: 'review' }],
    12: [{ title: 'Behind the scenes', type: 'Historias', status: 'review', need: 'Necesitamos 3 fotos' }],
    15: [{ title: 'Guía de hidratación', type: 'Carrusel', status: 'scheduled' }],
    18: [{ title: 'Testimonio Ana', type: 'Reel', status: 'scheduled' }],
    20: [{ title: 'Encuesta de piel', type: 'Historias', status: 'scheduled' }],
    23: [{ title: 'Ritual de noche', type: 'Reel', status: 'scheduled', need: 'Necesitamos tu voz' }],
    26: [{ title: 'Producto favorito', type: 'Post', status: 'scheduled' }],
    29: [{ title: 'Cierre del mes', type: 'Carrusel', status: 'scheduled' }],
};
function Logo({ compact = false }) {
    return createElement("div", { className: `logo ${compact ? 'compact' : ''}` },
        createElement("span", { className: "logo-mark" },
            createElement("i", null),
            createElement("i", null),
            createElement("i", null)),
        !compact && createElement("span", null,
            "biem",
            createElement("span", { className: "logo-dot" }, ".")));
}
function StatusPill({ status }) {
    const data = statusMap[status];
    return createElement("span", { className: `status-pill ${data.className}` },
        createElement("span", null),
        data.label);
}
function Sidebar({ active, setActive, open, setOpen }) {
    return createElement("aside", { className: `sidebar ${open ? 'open' : ''}` },
        createElement("div", { className: "sidebar-head" },
            createElement(Logo, null),
            createElement("button", { className: "mobile-close", onClick: () => setOpen(false), "aria-label": "Cerrar men\u00FA" },
                createElement(X, { size: 20 }))),
        createElement("div", { className: "client-switcher" },
            createElement("div", { className: "client-avatar" }, "AL"),
            createElement("div", null,
                createElement("small", null, "CUENTA ACTIVA"),
                createElement("strong", null, "Alma Studio")),
            createElement(ChevronDown, { size: 16 })),
        createElement("nav", null,
            createElement("span", { className: "nav-label" }, "ESPACIO DE TRABAJO"),
            navItems.map(item => {
                const Icon = item.icon;
                return createElement("button", { key: item.id, className: active === item.id ? 'active' : '', onClick: () => { setActive(item.id); setOpen(false); } },
                    createElement(Icon, { size: 19, strokeWidth: 1.8 }),
                    createElement("span", null, item.label),
                    item.badge && createElement("b", null, item.badge),
                    item.dot && createElement("i", { className: "unread-dot" }));
            })),
        createElement("div", { className: "sidebar-insight" },
            createElement("div", { className: "insight-icon" },
                createElement(Sparkles, { size: 17 })),
            createElement("span", null, "FOCO DEL MES"),
            createElement("strong", null, "Construir autoridad de marca"),
            createElement("p", null, "Contenido educativo + presencia humana."),
            createElement("div", { className: "progress" },
                createElement("i", { style: { width: '68%' } })),
            createElement("small", null, "68% del plan completado")),
        createElement("div", { className: "sidebar-user" },
            createElement("div", { className: "user-avatar" }, "MS"),
            createElement("div", null,
                createElement("strong", null, "Mar\u00EDa Santos"),
                createElement("span", null, "Cliente")),
            createElement(MoreHorizontal, { size: 19 })));
}
function Topbar({ active, setMenuOpen }) {
    const titles = { summary: 'Resumen del mes', deliverables: 'Entregables', calendar: 'Calendario de contenido', report: 'Reporte mensual', messages: 'Mensajes' };
    return createElement("header", { className: "topbar" },
        createElement("button", { className: "menu-btn", onClick: () => setMenuOpen(true), "aria-label": "Abrir men\u00FA" },
            createElement(Menu, { size: 22 })),
        createElement("div", null,
            createElement("span", null,
                "ALMA STUDIO ",
                createElement("i", null, "/")),
            createElement("strong", null, titles[active])),
        createElement("div", { className: "top-actions" },
            createElement("button", { className: "icon-button notification", "aria-label": "Notificaciones" },
                createElement(Bell, { size: 19 }),
                createElement("i", null)),
            createElement("div", { className: "top-avatar" }, "MS")));
}
function SectionHeading({ eyebrow, title, copy, actions }) {
    return createElement("div", { className: "section-heading" },
        createElement("div", null,
            createElement("span", { className: "eyebrow" }, eyebrow),
            createElement("h1", null, title),
            copy && createElement("p", null, copy)),
        actions && createElement("div", { className: "heading-actions" }, actions));
}
function Summary({ deliverables, onNavigate, approveReport, reportApproved }) {
    const pending = deliverables.filter(x => x.status === 'review').length;
    return createElement("div", { className: "page-content summary-page" },
        createElement(SectionHeading, { eyebrow: "JUNIO 2026", title: createElement(Fragment, null,
                "Buenos d\u00EDas, Mar\u00EDa ",
                createElement("span", { className: "wave" }, "\u2726")), copy: "Todo lo que estamos construyendo para Alma, en un solo lugar." }),
        createElement("section", { className: "hero-report" },
            createElement("div", { className: "hero-copy" },
                createElement("span", { className: "hero-kicker" },
                    createElement(Sparkles, { size: 14 }),
                    " REPORTE DE MAYO LISTO"),
                createElement("h2", null,
                    "Un mes de crecimiento",
                    createElement("br", null),
                    "que merece verse."),
                createElement("p", null, "Tu comunidad creci\u00F3 y el contenido educativo fue el gran protagonista."),
                createElement("div", { className: "hero-actions" },
                    createElement("button", { className: `primary-button light ${reportApproved ? 'approved-btn' : ''}`, onClick: approveReport }, reportApproved ? createElement(Fragment, null,
                        createElement(Check, { size: 17 }),
                        " Reporte aprobado") : createElement(Fragment, null,
                        "Revisar y aprobar ",
                        createElement(ArrowRight, { size: 17 }))),
                    createElement("button", { className: "text-button light", onClick: () => onNavigate('report') }, "Ver reporte completo"))),
            createElement("div", { className: "hero-visual" },
                createElement("div", { className: "orbit orbit-one" }),
                createElement("div", { className: "orbit orbit-two" }),
                createElement("div", { className: "metric-float reach" },
                    createElement(TrendingUp, { size: 15 }),
                    createElement("div", null,
                        createElement("strong", null, "+28%"),
                        createElement("span", null, "alcance"))),
                createElement("div", { className: "metric-float community" },
                    createElement(Users, { size: 15 }),
                    createElement("div", null,
                        createElement("strong", null, "+184"),
                        createElement("span", null, "comunidad"))),
                createElement("div", { className: "hero-phone" },
                    createElement("div", { className: "phone-notch" }),
                    createElement("div", { className: "phone-art" },
                        createElement("span", null, "alma"),
                        createElement("strong", null,
                            "Tu piel.",
                            createElement("br", null),
                            "Tu ritual."),
                        createElement("i", null))))),
        createElement("section", { className: "stats-grid" },
            createElement("article", null,
                createElement("div", { className: "stat-icon coral" },
                    createElement(FileText, { size: 20 })),
                createElement("div", null,
                    createElement("span", null, "PIEZAS DEL MES"),
                    createElement("strong", null,
                        "12 ",
                        createElement("small", null, "/ 16")),
                    createElement("p", null,
                        createElement("b", null, "75%"),
                        " del plan completado")),
                createElement("div", { className: "mini-progress" },
                    createElement("i", { style: { width: '75%' } }))),
            createElement("article", null,
                createElement("div", { className: "stat-icon amber" },
                    createElement(Clock3, { size: 20 })),
                createElement("div", null,
                    createElement("span", null, "POR TU APROBACI\u00D3N"),
                    createElement("strong", null, pending),
                    createElement("p", null, "Requieren de tu atenci\u00F3n")),
                createElement("button", { className: "round-arrow", onClick: () => onNavigate('deliverables') },
                    createElement(ArrowRight, { size: 17 }))),
            createElement("article", null,
                createElement("div", { className: "stat-icon mint" },
                    createElement(BarChart3, { size: 20 })),
                createElement("div", null,
                    createElement("span", null, "ALCANCE TOTAL"),
                    createElement("strong", null, "48.6K"),
                    createElement("p", { className: "positive" },
                        createElement(TrendingUp, { size: 13 }),
                        " 28% vs. abril")),
                createElement("div", { className: "sparkline" },
                    createElement("svg", { viewBox: "0 0 100 35" },
                        createElement("path", { d: "M0 30 C12 28, 15 18, 25 22 S40 30, 50 18 S64 18, 72 10 S88 14, 100 2", fill: "none", stroke: "currentColor", strokeWidth: "2.5" })))),
            createElement("article", null,
                createElement("div", { className: "stat-icon lavender" },
                    createElement(Users, { size: 20 })),
                createElement("div", null,
                    createElement("span", null, "COMUNIDAD"),
                    createElement("strong", null, "3,248"),
                    createElement("p", { className: "positive" },
                        createElement(TrendingUp, { size: 13 }),
                        " +184 este mes")),
                createElement("div", { className: "avatar-stack" },
                    createElement("i", null, "LA"),
                    createElement("i", null, "MC"),
                    createElement("i", null, "+")))),
        createElement("section", { className: "two-column" },
            createElement("div", { className: "panel pending-panel" },
                createElement("div", { className: "panel-title" },
                    createElement("div", null,
                        createElement("span", { className: "eyebrow" }, "TU ATENCI\u00D3N"),
                        createElement("h3", null, "Esperando tu aprobaci\u00F3n")),
                    createElement("button", { className: "text-button", onClick: () => onNavigate('deliverables') },
                        "Ver todos ",
                        createElement(ArrowRight, { size: 15 }))),
                createElement("div", { className: "approval-list" }, deliverables.filter(x => x.status === 'review').slice(0, 3).map(item => createElement("button", { key: item.id, onClick: () => onNavigate('deliverables'), className: "approval-item" },
                    createElement("div", { className: `thumb ${item.color}` },
                        createElement(item.icon, { size: 18 })),
                    createElement("div", null,
                        createElement("strong", null, item.title),
                        createElement("span", null,
                            item.type,
                            " \u00B7 Programado ",
                            item.date)),
                    createElement(StatusPill, { status: item.status }),
                    createElement(ArrowRight, { size: 16 }))))),
            createElement("div", { className: "panel meeting-panel" },
                createElement("div", { className: "panel-title" },
                    createElement("div", null,
                        createElement("span", { className: "eyebrow" }, "PR\u00D3XIMO EN AGENDA"),
                        createElement("h3", null, "Nuestra pr\u00F3xima reuni\u00F3n")),
                    createElement(CalendarDays, { size: 21 })),
                createElement("div", { className: "meeting-body" },
                    createElement("div", { className: "date-card" },
                        createElement("strong", null, "18"),
                        createElement("span", null, "JUN")),
                    createElement("div", null,
                        createElement("h4", null, "Revisi\u00F3n mensual + estrategia"),
                        createElement("p", null,
                            createElement(Clock3, { size: 14 }),
                            " 10:00 AM \u00B7 45 min"),
                        createElement("p", null,
                            createElement(Video, { size: 14 }),
                            " Google Meet"))),
                createElement("div", { className: "meeting-footer" },
                    createElement("div", { className: "attendees" },
                        createElement("i", null, "BI"),
                        createElement("i", null, "MS"),
                        createElement("span", null, "T\u00FA + equipo BIEM")),
                    createElement("button", { className: "secondary-button" }, "Ver agenda")))),
        createElement("section", { className: "focus-strip" },
            createElement("div", { className: "focus-icon" },
                createElement(Target, { size: 24 })),
            createElement("div", null,
                createElement("span", { className: "eyebrow" }, "ENFOQUE DE JUNIO"),
                createElement("h3", null, "Convertir conocimiento en confianza."),
                createElement("p", null, "Este mes posicionamos a Alma como referente a trav\u00E9s de contenido educativo, historias reales y una presencia m\u00E1s humana.")),
            createElement("div", { className: "focus-tags" },
                createElement("span", null, "01 \u00B7 EDUCAR"),
                createElement("span", null, "02 \u00B7 HUMANIZAR"),
                createElement("span", null, "03 \u00B7 CONVERTIR"))));
}
function DeliverableModal({ item, onClose, onApprove, onChanges }) {
    const [comment, setComment] = useState('');
    const [mode, setMode] = useState('view');
    return createElement("div", { className: "modal-backdrop", onMouseDown: onClose },
        createElement("div", { className: "deliverable-modal", onMouseDown: e => e.stopPropagation() },
            createElement("button", { className: "modal-close", onClick: onClose },
                createElement(X, { size: 20 })),
            createElement("div", { className: `modal-preview ${item.color}` },
                createElement("div", { className: "preview-brand" }, "alma"),
                createElement("span", null, item.tag),
                createElement("h2", null, item.caption),
                createElement("div", { className: "preview-product" },
                    createElement("i", null),
                    createElement("i", null),
                    createElement("i", null)),
                createElement("small", null, "@almastudio")),
            createElement("div", { className: "modal-details" },
                createElement("div", null,
                    createElement(StatusPill, { status: item.status }),
                    createElement("span", { className: "modal-date" },
                        "Programado \u00B7 ",
                        item.date)),
                createElement("h2", null, item.title),
                createElement("p", { className: "caption-label" }, "COPY PROPUESTO"),
                createElement("p", { className: "caption-copy" },
                    item.caption,
                    " Descubre una manera m\u00E1s consciente de cuidar de ti, un paso a la vez. \u2728"),
                createElement("div", { className: "meta-row" },
                    createElement("span", null,
                        createElement(Instagram, { size: 15 }),
                        " Instagram"),
                    createElement("span", null,
                        createElement(item.icon, { size: 15 }),
                        " ",
                        item.type)),
                mode === 'changes' ? createElement("div", { className: "comment-box" },
                    createElement("label", null, "\u00BFQu\u00E9 te gustar\u00EDa ajustar?"),
                    createElement("textarea", { autoFocus: true, value: comment, onChange: e => setComment(e.target.value), placeholder: "Escribe tu comentario para el equipo..." }),
                    createElement("div", null,
                        createElement("button", { className: "text-button", onClick: () => setMode('view') }, "Cancelar"),
                        createElement("button", { className: "primary-button", disabled: !comment.trim(), onClick: () => onChanges(item.id, comment) },
                            "Enviar cambios ",
                            createElement(Send, { size: 15 })))) : createElement("div", { className: "modal-actions" },
                    createElement("button", { className: "secondary-button", onClick: () => setMode('changes') },
                        createElement(PencilLine, { size: 16 }),
                        " Solicitar cambios"),
                    createElement("button", { className: "primary-button", onClick: () => onApprove(item.id) },
                        createElement(Check, { size: 17 }),
                        " Aprobar pieza")))));
}
function Deliverables({ deliverables, setDeliverables }) {
    const [filter, setFilter] = useState('all');
    const [selected, setSelected] = useState(null);
    const visible = filter === 'all' ? deliverables : deliverables.filter(x => x.status === filter);
    const approve = id => { setDeliverables(items => items.map(x => x.id === id ? { ...x, status: 'approved' } : x)); setSelected(null); };
    const changes = (id) => { setDeliverables(items => items.map(x => x.id === id ? { ...x, status: 'changes' } : x)); setSelected(null); };
    return createElement("div", { className: "page-content" },
        createElement(SectionHeading, { eyebrow: "CONTENIDO DE JUNIO", title: "Entregables", copy: "Revisa cada pieza, deja tus comentarios y aprueba sin salir del portal.", actions: createElement("button", { className: "primary-button" },
                createElement(Plus, { size: 17 }),
                " Solicitar pieza") }),
        createElement("div", { className: "filter-row" }, [['all', 'Todos'], ['review', 'Por revisar'], ['approved', 'Aprobados'], ['published', 'Publicados']].map(([id, label]) => createElement("button", { key: id, className: filter === id ? 'active' : '', onClick: () => setFilter(id) },
            label,
            createElement("span", null, id === 'all' ? deliverables.length : deliverables.filter(x => x.status === id).length)))),
        createElement("div", { className: "deliverable-grid" }, visible.map(item => createElement("article", { className: "deliverable-card", key: item.id, onClick: () => setSelected(item) },
            createElement("div", { className: `deliverable-art ${item.color}` },
                createElement("span", { className: "art-tag" }, item.tag),
                createElement("strong", null, item.caption),
                createElement("div", { className: "art-shapes" },
                    createElement("i", null),
                    createElement("i", null),
                    createElement("i", null)),
                createElement("span", { className: "art-brand" }, "alma"),
                createElement("div", { className: "card-hover" },
                    createElement(ArrowRight, { size: 21 }))),
            createElement("div", { className: "deliverable-info" },
                createElement("div", null,
                    createElement(StatusPill, { status: item.status }),
                    createElement("button", { onClick: e => e.stopPropagation() },
                        createElement(MoreHorizontal, { size: 18 }))),
                createElement("h3", null, item.title),
                createElement("p", null,
                    createElement(item.icon, { size: 14 }),
                    " ",
                    item.type,
                    createElement("span", null),
                    item.date))))),
        visible.length === 0 && createElement("div", { className: "empty-state" },
            createElement(CheckCircle2, { size: 36 }),
            createElement("h3", null, "Todo al d\u00EDa"),
            createElement("p", null, "No hay entregables en este estado.")),
        selected && createElement(DeliverableModal, { item: deliverables.find(x => x.id === selected.id), onClose: () => setSelected(null), onApprove: approve, onChanges: changes }));
}
function CalendarPage() {
    const [view, setView] = useState('month');
    const days = useMemo(() => Array.from({ length: 35 }, (_, i) => i < 1 || i > 30 ? null : i), []);
    return createElement("div", { className: "page-content calendar-page" },
        createElement(SectionHeading, { eyebrow: "PLAN DE CONTENIDO", title: "Calendario de junio", copy: "Qu\u00E9 publicamos, cu\u00E1ndo sale y qu\u00E9 necesitamos de tu parte.", actions: createElement("div", { className: "calendar-controls" },
                createElement("button", null,
                    createElement(ArrowLeft, { size: 17 })),
                createElement("button", null, "Hoy"),
                createElement("button", null,
                    createElement(ArrowRight, { size: 17 }))) }),
        createElement("div", { className: "calendar-toolbar" },
            createElement("div", { className: "legend" },
                createElement("span", null,
                    createElement("i", { className: "published" }),
                    "Publicado"),
                createElement("span", null,
                    createElement("i", { className: "approved" }),
                    "Aprobado"),
                createElement("span", null,
                    createElement("i", { className: "review" }),
                    "Por revisar"),
                createElement("span", null,
                    createElement("i", { className: "scheduled" }),
                    "Programado")),
            createElement("div", { className: "view-toggle" },
                createElement("button", { className: view === 'month' ? 'active' : '', onClick: () => setView('month') }, "Mes"),
                createElement("button", { className: view === 'list' ? 'active' : '', onClick: () => setView('list') }, "Lista"))),
        view === 'month' ? createElement("div", { className: "calendar-shell" },
            createElement("div", { className: "weekdays" }, ['LUN', 'MAR', 'MIÉ', 'JUE', 'VIE', 'SÁB', 'DOM'].map(x => createElement("span", { key: x }, x))),
            createElement("div", { className: "calendar-grid" }, days.map((day, i) => createElement("div", { className: `calendar-day ${!day ? 'muted' : ''}`, key: i }, day && createElement(Fragment, null,
                createElement("span", { className: day === 6 ? 'today' : '' }, day),
                calendarEvents[day]?.map((event, j) => createElement("div", { className: `calendar-event ${event.status}`, key: j },
                    createElement("strong", null, event.title),
                    createElement("small", null, event.type),
                    event.need && createElement("em", null,
                        createElement(Zap, { size: 10 }),
                        " ",
                        event.need)))))))) : createElement("div", { className: "calendar-list" }, Object.entries(calendarEvents).map(([day, events]) => events.map(event => createElement("article", { key: `${day}-${event.title}` },
            createElement("div", { className: "list-date" },
                createElement("strong", null, day),
                createElement("span", null, "JUN")),
            createElement("div", null,
                createElement(StatusPill, { status: event.status }),
                createElement("h3", null, event.title),
                createElement("p", null,
                    event.type,
                    event.need && ` · ${event.need}`)),
            createElement("button", { className: "round-arrow" },
                createElement(ArrowRight, { size: 16 })))))));
}
function Report({ approved, onApprove }) {
    return createElement("div", { className: "page-content report-page" },
        createElement(SectionHeading, { eyebrow: "RESULTADOS \u00B7 MAYO 2026", title: "Reporte mensual", copy: "El impacto del trabajo, explicado con claridad.", actions: createElement("button", { className: "secondary-button" },
                createElement(Download, { size: 17 }),
                " Descargar PDF") }),
        createElement("section", { className: "report-hero" },
            createElement("div", null,
                createElement("span", { className: "eyebrow light-text" }, "LA HISTORIA DEL MES"),
                createElement("h2", null,
                    "M\u00E1s alcance.",
                    createElement("br", null),
                    "M\u00E1s conversaci\u00F3n.",
                    createElement("br", null),
                    createElement("i", null, "M\u00E1s Alma.")),
                createElement("p", null, "El contenido educativo acerc\u00F3 la marca a una comunidad que no solo mira: guarda, comparte y participa.")),
            createElement("div", { className: "big-number" },
                createElement("span", null, "ALCANCE TOTAL"),
                createElement("strong", null, "48,624"),
                createElement("p", null,
                    createElement(TrendingUp, { size: 16 }),
                    " +28% frente a abril"),
                createElement("svg", { viewBox: "0 0 300 90" },
                    createElement("path", { d: "M0 76 C30 72 38 58 70 63 S115 78 143 43 S182 52 211 29 S257 34 300 5", fill: "none", stroke: "currentColor", strokeWidth: "3" })))),
        createElement("section", { className: "report-metrics" },
            createElement("article", null,
                createElement("span", null, "IMPRESIONES"),
                createElement("strong", null, "72.4K"),
                createElement("p", null,
                    "+18.2% ",
                    createElement("small", null, "vs. abril"))),
            createElement("article", null,
                createElement("span", null, "INTERACCIONES"),
                createElement("strong", null, "3,842"),
                createElement("p", null,
                    "+34.5% ",
                    createElement("small", null, "vs. abril"))),
            createElement("article", null,
                createElement("span", null, "ENGAGEMENT"),
                createElement("strong", null, "7.9%"),
                createElement("p", null,
                    "+1.8 pts ",
                    createElement("small", null, "vs. abril"))),
            createElement("article", null,
                createElement("span", null, "NUEVOS SEGUIDORES"),
                createElement("strong", null, "+184"),
                createElement("p", null,
                    "+22.6% ",
                    createElement("small", null, "vs. abril")))),
        createElement("section", { className: "report-columns" },
            createElement("div", { className: "panel top-content" },
                createElement("div", { className: "panel-title" },
                    createElement("div", null,
                        createElement("span", { className: "eyebrow" }, "LO QUE FUNCION\u00D3"),
                        createElement("h3", null, "Contenido con mayor impacto"))),
                createElement("div", { className: "winner" },
                    createElement("div", { className: "winner-art" },
                        createElement("span", null, "3 pasos"),
                        createElement("strong", null,
                            "para una piel",
                            createElement("br", null),
                            "m\u00E1s luminosa"),
                        createElement("i", null, "alma")),
                    createElement("div", null,
                        createElement("span", { className: "winner-badge" }, "#1 DEL MES"),
                        createElement("h4", null, "Carrusel educativo"),
                        createElement("p", null, "\u201C3 pasos para una piel m\u00E1s luminosa\u201D"),
                        createElement("div", { className: "winner-stats" },
                            createElement("span", null,
                                createElement("strong", null, "12.8K"),
                                " alcance"),
                            createElement("span", null,
                                createElement("strong", null, "684"),
                                " guardados"),
                            createElement("span", null,
                                createElement("strong", null, "9.2%"),
                                " engagement"))))),
            createElement("div", { className: "panel learnings" },
                createElement("span", { className: "eyebrow" }, "APRENDIZAJES"),
                createElement("h3", null, "Qu\u00E9 nos dicen los datos"),
                createElement("ul", null,
                    createElement("li", null,
                        createElement("div", null,
                            createElement(Sparkles, { size: 17 })),
                        createElement("p", null,
                            createElement("strong", null, "Educar genera confianza."),
                            " Los carruseles educativos obtuvieron 2.4\u00D7 m\u00E1s guardados.")),
                    createElement("li", null,
                        createElement("div", null,
                            createElement(UserRound, { size: 17 })),
                        createElement("p", null,
                            createElement("strong", null, "Queremos verte m\u00E1s."),
                            " El contenido con presencia humana aument\u00F3 41% la interacci\u00F3n.")),
                    createElement("li", null,
                        createElement("div", null,
                            createElement(MessageCircle, { size: 17 })),
                        createElement("p", null,
                            createElement("strong", null, "La comunidad pregunta."),
                            " Recibimos 32 consultas sobre rutinas personalizadas."))))),
        createElement("section", { className: "next-month" },
            createElement("div", null,
                createElement("span", { className: "eyebrow" }, "PR\u00D3XIMO MES"),
                createElement("h2", null,
                    "De la atenci\u00F3n a la ",
                    createElement("i", null, "conversi\u00F3n.")),
                createElement("p", null, "En junio vamos a profundizar la autoridad de Alma e introducir llamadas a la acci\u00F3n m\u00E1s claras.")),
            createElement("div", { className: "strategy-steps" },
                createElement("span", null,
                    createElement("b", null, "01"),
                    "M\u00E1s videos con Mar\u00EDa"),
                createElement("span", null,
                    createElement("b", null, "02"),
                    "Serie educativa semanal"),
                createElement("span", null,
                    createElement("b", null, "03"),
                    "Activar consultas por DM"))),
        createElement("section", { className: `approval-banner ${approved ? 'done' : ''}` },
            createElement("div", { className: "approval-check" }, approved ? createElement(Check, { size: 23 }) : createElement(FileBarChart, { size: 23 })),
            createElement("div", null,
                createElement("h3", null, approved ? 'Reporte aprobado' : '¿Todo claro con el reporte?'),
                createElement("p", null, approved ? 'Gracias. Tu aprobación quedó registrada para el equipo BIEM.' : 'Tu aprobación nos permite avanzar con el enfoque de junio.')),
            createElement("button", { className: "primary-button", onClick: onApprove }, approved ? createElement(Fragment, null,
                createElement(CheckCircle2, { size: 17 }),
                " Aprobado") : createElement(Fragment, null,
                "Aprobar reporte ",
                createElement(ArrowRight, { size: 17 })))));
}
function Messages() {
    const [text, setText] = useState('');
    const [messages, setMessages] = useState([
        { from: 'biem', text: '¡Hola, María! Te compartimos las primeras piezas de junio. Hay 3 listas para tu revisión ✨', time: '9:42 AM' },
        { from: 'client', text: '¡Perfecto! Las revisaré esta mañana. Me encanta cómo viene tomando forma la campaña.', time: '10:08 AM' },
        { from: 'biem', text: 'Nos alegra mucho. Para el reel del día 8 solo nos faltaría tu video; te dejamos la guía aquí.', time: '10:12 AM', file: 'Guía_video_reel.pdf · 1.2 MB' },
    ]);
    const send = () => { if (!text.trim())
        return; setMessages([...messages, { from: 'client', text: text.trim(), time: 'Ahora' }]); setText(''); };
    return createElement("div", { className: "page-content messages-page" },
        createElement(SectionHeading, { eyebrow: "CANAL DIRECTO", title: "Mensajes", copy: "Todas las conversaciones del proyecto, ordenadas y en contexto." }),
        createElement("div", { className: "message-layout" },
            createElement("aside", { className: "conversation-list" },
                createElement("div", { className: "conversation-search" },
                    "Conversaciones ",
                    createElement("button", null,
                        createElement(Plus, { size: 16 }))),
                createElement("button", { className: "conversation active" },
                    createElement("div", { className: "conversation-avatar" }, "BI"),
                    createElement("div", null,
                        createElement("strong", null, "Equipo BIEM"),
                        createElement("p", null, "Nos alegra mucho. Para el reel...")),
                    createElement("span", null, "10:12"),
                    createElement("i", null, "2")),
                createElement("button", { className: "conversation" },
                    createElement("div", { className: "conversation-avatar strategy" },
                        createElement(Target, { size: 18 })),
                    createElement("div", null,
                        createElement("strong", null, "Estrategia junio"),
                        createElement("p", null, "Camila: Actualic\u00E9 el enfoque...")),
                    createElement("span", null, "Ayer"))),
            createElement("section", { className: "chat" },
                createElement("header", null,
                    createElement("div", { className: "conversation-avatar" }, "BI"),
                    createElement("div", null,
                        createElement("strong", null, "Equipo BIEM"),
                        createElement("span", null,
                            createElement("i", null),
                            " 3 miembros \u00B7 En l\u00EDnea")),
                    createElement("button", { className: "icon-button" },
                        createElement(MoreHorizontal, { size: 19 }))),
                createElement("div", { className: "chat-body" },
                    createElement("div", { className: "date-divider" },
                        createElement("span", null, "HOY, 6 DE JUNIO")),
                    messages.map((message, index) => createElement("div", { key: index, className: `message ${message.from}` },
                        createElement("div", { className: "message-avatar" }, message.from === 'biem' ? 'BI' : 'MS'),
                        createElement("div", null,
                            createElement("small", null,
                                message.from === 'biem' ? 'Equipo BIEM' : 'Tú',
                                " \u00B7 ",
                                message.time),
                            createElement("p", null, message.text),
                            message.file && createElement("button", { className: "file-attachment" },
                                createElement(FileText, { size: 21 }),
                                createElement("span", null,
                                    createElement("strong", null, "Gu\u00EDa para grabar tu reel"),
                                    createElement("small", null, message.file)),
                                createElement(Download, { size: 16 })))))),
                createElement("div", { className: "message-compose" },
                    createElement("button", null,
                        createElement(Paperclip, { size: 20 })),
                    createElement("textarea", { value: text, onChange: e => setText(e.target.value), onKeyDown: e => { if (e.key === 'Enter' && !e.shiftKey) {
                            e.preventDefault();
                            send();
                        } }, placeholder: "Escribe un mensaje al equipo...", rows: "1" }),
                    createElement("button", { className: "send-button", onClick: send, disabled: !text.trim() },
                        createElement(Send, { size: 18 }))))));
}
export default function App() {
    const [active, setActive] = useState('summary');
    const [menuOpen, setMenuOpen] = useState(false);
    const [deliverables, setDeliverables] = useState(initialDeliverables);
    const [reportApproved, setReportApproved] = useState(false);
    const content = {
        summary: createElement(Summary, { deliverables: deliverables, onNavigate: setActive, approveReport: () => setReportApproved(true), reportApproved: reportApproved }),
        deliverables: createElement(Deliverables, { deliverables: deliverables, setDeliverables: setDeliverables }),
        calendar: createElement(CalendarPage, null),
        report: createElement(Report, { approved: reportApproved, onApprove: () => setReportApproved(true) }),
        messages: createElement(Messages, null),
    };
    return createElement("div", { className: "app-shell" },
        createElement(Sidebar, { active: active, setActive: setActive, open: menuOpen, setOpen: setMenuOpen }),
        menuOpen && createElement("div", { className: "sidebar-overlay", onClick: () => setMenuOpen(false) }),
        createElement("main", null,
            createElement(Topbar, { active: active, setMenuOpen: setMenuOpen }),
            content[active]));
}
