import { createElement, Fragment, useEffect, useState } from './mini-react.js'
import { AlertTriangle, ArrowLeft, Bell, Briefcase, CalendarDays, Check, CheckCircle2, Clock3, CreditCard, FileText, Grid2X2, LayoutDashboard, LogOut, Menu, MessageCircle, Palette, Plus, Receipt, Send, Sparkles, UserRound, X } from './icons.jsx'
import { createClientRequest, loadPortalWorkspace, requestEventReschedule, reviewClientDeliverable, saveBrandBasics, saveNotificationPreferences, uploadBrandLogo } from './lib/portal-api.js'

const empty={account:null,brand:null,events:[],deliverables:[],invoices:[],requests:[],tasks:[],resources:[],services:[],preferences:null}
const labels={pending:'Pendiente',paid:'Pagada',overdue:'Vencida',approved:'Aprobado',published:'Publicado',client_review:'Por revisar',changes_requested:'Cambios solicitados',scheduled:'Programada',reschedule_requested:'Reagenda solicitada',cancelled:'Cancelada',completed:'Completada',new:'Nueva',in_review:'En revisión'}
function initials(value='BI'){return value.split(/\s+/).filter(Boolean).map(word=>word[0]).join('').slice(0,2).toUpperCase()}
function date(value){return value?new Intl.DateTimeFormat('es',{dateStyle:'medium',timeStyle:value.includes?.('T')?'short':undefined}).format(new Date(value.length===10?`${value}T12:00:00`:value)):'Sin fecha'}
function money(value,currency='USD'){return new Intl.NumberFormat('es',{style:'currency',currency}).format(Number(value||0))}
function LogoAvatar({brand,size='normal'}){return brand?.brand_logo_url?<img className={`brand-logo ${size}`} src={brand.brand_logo_url} alt={`Logo ${brand.brand_name||''}`}/>:<div className={`brand-logo fallback ${size}`}>{initials(brand?.brand_name)}</div>}

export default function ClientPortalApp({profile,onSignOut,previewData=null,previewClientId=null,onExitPreview}){
  const preview=Boolean(previewData),[data,setData]=useState(previewData?normalizePreview(previewData):empty),[loading,setLoading]=useState(!previewData),[error,setError]=useState(''),[notice,setNotice]=useState(''),[active,setActive]=useState('summary'),[menu,setMenu]=useState(false),[revision,setRevision]=useState(0),[modal,setModal]=useState('')
  useEffect(()=>{if(preview)return;let alive=true;setLoading(true);loadPortalWorkspace(profile).then(result=>{if(alive){setData(result);setError('')}}).catch(reason=>{if(alive)setError(reason.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[revision,profile.id])
  const mutate=async(operation,message)=>{setError('');try{await operation();setNotice(message);setModal('');if(!preview)setRevision(v=>v+1)}catch(reason){console.error('[BIEM client portal]',reason);setError(reason.message)}}
  const brand=data.brand||{brand_name:data.account?.brand_name}
  const nav=[['summary','Resumen',LayoutDashboard],['brand','Perfil de marca',Palette],['deliverables','Entregables',Grid2X2],['requests','Solicitudes',MessageCircle],['calendar','Reuniones',CalendarDays],['billing','Facturación',Receipt],['strategy','Estrategia',Sparkles],['notifications','Notificaciones',Bell]]
  const panels={
    summary:<Summary data={data} brand={brand} setActive={setActive}/>,
    brand:<BrandProfile brand={brand} editable={!preview&&!data.account?.onboarding_completed} profile={profile} mutate={mutate}/>,
    deliverables:<Deliverables items={data.deliverables} preview={preview} mutate={mutate}/>,
    requests:<Requests items={data.requests} preview={preview} onCreate={()=>setModal('request')}/>,
    calendar:<Calendar events={data.events} preview={preview} mutate={mutate}/>,
    billing:<Billing invoices={data.invoices}/>,
    strategy:<Strategy resources={data.resources} tasks={data.tasks}/>,
    notifications:<Notifications preferences={data.preferences} preview={preview} profile={profile} mutate={mutate}/>,
  }
  return <div className={`client-portal-shell ${preview?'is-preview':''}`}>{preview&&<div className="preview-bar"><span>Estás viendo este portal como admin. Cliente: <strong>{data.account?.brand_name}</strong></span><button onClick={onExitPreview}><ArrowLeft size={15}/>Volver al panel admin</button></div>}<aside className={menu?'open':''}><header><strong>biem.</strong><button onClick={()=>setMenu(false)}><X/></button></header><div className="portal-brand-switch"><LogoAvatar brand={brand}/><div><small>PORTAL PRIVADO</small><strong>{brand?.brand_name||data.account?.brand_name||'Tu marca'}</strong></div></div><nav>{nav.map(([id,label,Icon])=><button className={active===id?'active':''} onClick={()=>{setActive(id);setMenu(false)}} key={id}><Icon size={17}/>{label}</button>)}</nav>{!preview&&<button className="portal-signout" onClick={onSignOut}><LogOut size={16}/>Cerrar sesión</button>}</aside><main><header className="portal-topbar"><button onClick={()=>setMenu(true)}><Menu/></button><div><small>BIEM DIGITAL</small><strong>{nav.find(item=>item[0]===active)?.[1]}</strong></div><LogoAvatar brand={brand} size="small"/></header><div className="portal-page">{loading&&<div className="data-feedback loading">Cargando tu portal...</div>}{error&&<div className="data-feedback error"><AlertTriangle size={16}/>{error}</div>}{notice&&<div className="data-feedback success"><CheckCircle2 size={16}/>{notice}</div>}{preview&&previewData?.confidentiality?.active_agreement&&!previewData.confidentiality.accepted&&<div className="portal-warning"><AlertTriangle/>Este cliente todavía debe aceptar la versión {previewData.confidentiality.active_agreement.version} del compromiso de confidencialidad.</div>}{preview&&!data.account?.onboarding_completed&&<div className="portal-warning"><Clock3/>El onboarding o confirmación de datos está pendiente: {data.account?.onboarding_type||'sin clasificar'}.</div>}{panels[active]}</div></main>{menu&&<div className="portal-overlay" onClick={()=>setMenu(false)}/>} {modal==='request'&&<RequestModal onClose={()=>setModal('')} onSubmit={payload=>mutate(()=>createClientRequest(profile,payload),'Solicitud enviada. También recibirás confirmación por correo.')}/>}</div>
}

function normalizePreview(value){return {account:value.account,brand:value.brand,deliverables:value.deliverables||[],invoices:value.invoices||[],requests:value.requests||[],resources:value.resources||[],events:value.events||[],tasks:[],services:[],preferences:null}}
function Summary({data,brand,setActive}){const next=data.events.find(event=>event.status==='scheduled');return <><div className="portal-welcome"><div><span>RESUMEN DE TU CUENTA</span><h1>Hola, {data.account?.name||'bienvenido/a'}</h1><p>Todo el avance de {brand?.brand_name||data.account?.brand_name} en un solo lugar.</p></div><LogoAvatar brand={brand} size="large"/></div><div className="portal-summary-grid"><button onClick={()=>setActive('brand')}><Palette/><span>Perfil de marca</span><strong>{brand?.brand_name||'Completar perfil'}</strong><small>{brand?.industry||'Información de tu marca'}</small></button><button onClick={()=>setActive('deliverables')}><Grid2X2/><span>Entregables</span><strong>{data.deliverables.length}</strong><small>{data.deliverables.filter(i=>i.status==='client_review').length} por revisar</small></button><button onClick={()=>setActive('requests')}><MessageCircle/><span>Solicitudes</span><strong>{data.requests.length}</strong><small>{data.requests.filter(i=>['new','in_review'].includes(i.status)).length} abiertas</small></button><button onClick={()=>setActive('calendar')}><CalendarDays/><span>Próxima reunión</span><strong>{next?date(next.start_time):'Sin agendar'}</strong><small>{next?.title||'Coordina con tu agente'}</small></button></div><section className="portal-card"><header><div><span>PRÓXIMOS PASOS</span><h2>Lo que sigue</h2></div></header>{data.tasks.length?data.tasks.slice(0,4).map(task=><div className="portal-list-row" key={task.id}><CheckCircle2/><div><strong>{task.title}</strong><small>{task.description||date(task.due_date)}</small></div><b>{labels[task.status]||task.status}</b></div>):<div className="portal-empty">No hay pendientes visibles por ahora.</div>}</section></>}
function BrandProfile({brand,editable,profile,mutate}){const [editing,setEditing]=useState(false);const submit=event=>{event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));mutate(()=>saveBrandBasics(payload),'Perfil de marca actualizado.');setEditing(false)};const upload=async event=>{const file=event.target.files?.[0];if(!file)return;const url=await uploadBrandLogo(profile,file);await mutate(()=>saveBrandBasics({brand_logo_url:url}),'Logo actualizado.')};return <div className="brand-profile-page"><div className="brand-cover" style={brand?.brand_cover_image_url?{backgroundImage:`url(${brand.brand_cover_image_url})`}:undefined}><LogoAvatar brand={brand} size="hero"/><div><span>PERFIL DE MARCA</span><h1>{brand?.brand_name||'Tu marca'}</h1><p>{brand?.industry||'Industria por completar'}</p></div>{editable&&<button onClick={()=>setEditing(!editing)}>Editar datos básicos</button>}</div>{editing?<form className="brand-edit-form" onSubmit={submit}><input name="brand_name" value={brand?.brand_name||''} placeholder="Nombre de marca"/><input name="industry" value={brand?.industry||''} placeholder="Industria"/><textarea name="brand_summary" value={brand?.brand_summary||''} placeholder="Descripción corta"/><textarea name="brand_about" value={brand?.brand_about||''} placeholder="Sobre la marca"/><input name="website_url" value={brand?.website_url||''} placeholder="Sitio web"/><input name="instagram_url" value={brand?.instagram_url||''} placeholder="Instagram"/><input name="whatsapp_number" value={brand?.whatsapp_number||''} placeholder="WhatsApp"/><input type="file" accept="image/*" onChange={upload}/><button className="admin-primary">Guardar cambios</button></form>:<><section className="brand-about-card"><span>SOBRE LA MARCA</span><h2>Sobre {brand?.brand_name||'tu marca'}</h2><p>{brand?.brand_about||brand?.brand_summary||`${brand?.brand_name||'Esta marca'} está construyendo una presencia clara y consistente junto a Biem Digital.`}</p></section><div className="brand-detail-grid">{[['Qué ofrece',brand?.main_products_services],['Público objetivo',brand?.target_audience],['Propuesta de valor',brand?.value_proposition],['Tono de comunicación',brand?.communication_tone],['Tipografías',brand?.typography],['Ubicación',brand?.location]].map(([title,value])=><article key={title}><span>{title}</span><p>{value||'Por completar'}</p></article>)}</div><section className="portal-card"><header><div><span>ENLACES PRINCIPALES</span><h2>Presencia digital</h2></div></header><div className="brand-links">{[['Sitio web',brand?.website_url],['Instagram',brand?.instagram_url],['Facebook',brand?.facebook_url],['TikTok',brand?.tiktok_url],['WhatsApp',brand?.whatsapp_number]].filter(([,value])=>value).map(([label,value])=><a href={value.startsWith?.('http')?value:`https://wa.me/${value}`} target="_blank" key={label}>{label}</a>)}</div></section></>}</div>}
function Deliverables({items,preview,mutate}){return <section className="portal-card"><header><div><span>CONTENIDO</span><h1>Entregables</h1></div></header>{items.map(item=><div className="portal-list-row deliverable-with-assets" key={item.id}><Grid2X2/><div><strong>{item.name}</strong><small>{item.content_type} · {date(item.due_date)}</small>{item.client_comments&&<p>{item.client_comments}</p>}{item.drive_assets?.length>0&&<div className="portal-drive-assets"><span>ARCHIVOS EN GOOGLE DRIVE</span>{item.drive_assets.map(asset=><a href={asset.drive_url} target="_blank" rel="noopener noreferrer" key={asset.id}><FileText size={15}/><div><strong>{asset.name}</strong><small>{asset.asset_type}{asset.is_primary?' · Principal':''}</small></div><ArrowLeft className="drive-arrow" size={14}/></a>)}</div>}</div><b>{labels[item.status]||item.status}</b>{!preview&&item.status==='client_review'&&<span className="row-actions"><button onClick={()=>mutate(()=>reviewClientDeliverable(item.id,'approved'),'Entregable aprobado.')}>Aprobar</button><button onClick={()=>{const comment=window.prompt('Indica los cambios solicitados');if(comment)mutate(()=>reviewClientDeliverable(item.id,'changes_requested',comment),'Cambios solicitados.')}}>Solicitar cambios</button></span>}</div>)}{!items.length&&<div className="portal-empty">Aún no hay entregables visibles.</div>}</section>}
function Requests({items,preview,onCreate}){return <section className="portal-card"><header><div><span>SEGUIMIENTO</span><h1>Solicitudes</h1></div>{!preview&&<button className="admin-primary" onClick={onCreate}><Plus/>Nueva solicitud</button>}</header>{items.map(item=><div className="portal-list-row" key={item.id}><MessageCircle/><div><strong>{item.request_type}</strong><small>{date(item.created_at)}</small><p>{item.description}</p>{item.admin_response&&<p className="portal-response">Biem: {item.admin_response}</p>}</div><b>{labels[item.status]||item.status}</b></div>)}{!items.length&&<div className="portal-empty">No hay solicitudes.</div>}</section>}
function Calendar({events,preview,mutate}){return <section className="portal-card"><header><div><span>AGENDA</span><h1>Próximas reuniones</h1></div></header>{events.map(event=><div className="portal-event" key={event.id}><div className="event-date"><CalendarDays/><strong>{date(event.start_time)}</strong></div><div><h3>{event.title}</h3><p>{event.description}</p><small>{event.location||'Reunión online'} · {event.timezone}</small></div><div>{event.google_meet_link&&<a href={event.google_meet_link} target="_blank">Entrar a Google Meet</a>} {!preview&&event.status==='scheduled'&&<button onClick={()=>{const note=window.prompt('¿Qué fecha u horario prefieres?');if(note)mutate(()=>requestEventReschedule(event.id,note),'Solicitud de reagenda enviada.')}}>Solicitar reagenda</button>}<b>{labels[event.status]||event.status}</b></div></div>)}{!events.length&&<div className="portal-empty">No hay reuniones programadas.</div>}</section>}
function Billing({invoices}){return <section className="portal-card"><header><div><span>CUENTA</span><h1>Facturación</h1></div></header>{invoices.map(item=><div className="portal-list-row" key={item.id}><CreditCard/><div><strong>{item.invoice_number}</strong><small>Vence {date(item.due_date)}</small></div><strong>{money(item.amount,item.currency)}</strong><b>{labels[item.status]||item.status}</b></div>)}{!invoices.length&&<div className="portal-empty">No hay facturas disponibles.</div>}</section>}
function Strategy({resources,tasks}){return <><section className="portal-card"><header><div><span>ESTRATEGIA</span><h1>Recomendaciones y diagnóstico</h1></div></header>{resources.map(item=><article className="strategy-card" key={item.id}><span>{item.resource_type}</span><h3>{item.title}</h3><p>{item.content}</p>{item.file_url&&<a href={item.file_url} target="_blank">Abrir recurso</a>}</article>)}{!resources.length&&<div className="portal-empty">No hay recomendaciones visibles todavía.</div>}</section></>}
function Notifications({preferences,preview,profile,mutate}){const values=preferences||{email_enabled:true,request_updates:true,deliverable_updates:true,invoice_updates:true,recommendation_updates:true,calendar_updates:true};const submit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);const payload={};['email_enabled','request_updates','deliverable_updates','invoice_updates','recommendation_updates','calendar_updates'].forEach(key=>payload[key]=form.get(key)==='on');mutate(()=>saveNotificationPreferences(profile,payload),'Preferencias guardadas.')};return <section className="portal-card"><header><div><span>COMUNICACIÓN</span><h1>Notificaciones por correo</h1></div></header><form className="notification-form" onSubmit={submit}>{[['email_enabled','Recibir correos del portal'],['request_updates','Actualizaciones de solicitudes'],['deliverable_updates','Entregables listos'],['invoice_updates','Facturas y recordatorios'],['recommendation_updates','Recomendaciones estratégicas'],['calendar_updates','Reuniones y calendario']].map(([key,label])=><label key={key}><input type="checkbox" name={key} checked={values[key]}/><span>{label}</span></label>)}{!preview&&<button className="admin-primary">Guardar preferencias</button>}</form></section>}
function RequestModal({onClose,onSubmit}){const submit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));onSubmit({...values,priority:'medium'})};return <div className="modal-backdrop" onMouseDown={onClose}><form className="portal-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><h2>Nueva solicitud</h2><button type="button" onClick={onClose}><X/></button></header><label>Título<input name="request_type" required/></label><label>Descripción<textarea name="description" required/></label><label>Fecha deseada<input name="desired_due_date" type="date"/></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className="admin-primary"><Send/>Enviar solicitud</button></footer></form></div>}
