import { createElement, Fragment, useEffect, useMemo, useState } from './mini-react.js'
import { AlertTriangle, Briefcase, CalendarDays, CheckCircle2, Clock3, FileText, Grid2X2, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Send, UserRound, Users, X } from './icons.jsx'
import { createTeamDeliverable, createTeamDriveAsset, deleteTeamDriveAsset, createTeamNote, createTeamResource, createTeamTask, loadTeamWorkspace, respondToRequest, updateTeamDeliverable, updateTeamTask } from './lib/team-api.js'

const roleMeta={
  account_manager:{label:'Agente de cuenta',path:'/team/account-manager',intro:'Coordina clientes, solicitudes y trabajo del equipo.'},
  designer:{label:'Diseño gráfico',path:'/team/designer',intro:'Gestiona tus tareas visuales y entregables asignados.'},
  social_media:{label:'Social media',path:'/team/social-media',intro:'Organiza publicaciones, calendario y evidencias.'},
  video_editor:{label:'Edición de video',path:'/team/video-editor',intro:'Gestiona briefs, revisiones y entregas de video.'},
}
const statusLabels={pending:'Pendiente',in_progress:'En proceso',ready_for_review:'Listo para revisión',changes_requested:'Cambios solicitados',corrected:'Corregido',completed:'Completado',paused:'Pausado',internal_review:'Revisión interna',client_review:'Revisión cliente',approved:'Aprobado',published:'Publicado',new:'Nueva',in_review:'En revisión'}
const taskStatuses=['pending','in_progress','ready_for_review','changes_requested','corrected','completed','paused']
const deliverableStatuses={account_manager:['pending','in_progress','internal_review','client_review','changes_requested','approved','published'],designer:['pending','in_progress','internal_review','changes_requested','approved'],social_media:['approved','published'],video_editor:['pending','in_progress','internal_review','changes_requested','approved']}
const empty={clients:[],tasks:[],deliverables:[],requests:[],resources:[],notes:[]}

function formatDate(value){if(!value)return 'Sin fecha';return new Intl.DateTimeFormat('es',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}`.length===10?`${value}T12:00:00`:value))}
function initials(value='BI'){return value.split(/\s+/).filter(Boolean).map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function Badge({value}){return <span className={`team-status ${value}`}>{statusLabels[value]||value}</span>}

function useTeamWorkspace(profile){
  const [data,setData]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0)
  useEffect(()=>{let active=true;setLoading(true);loadTeamWorkspace(profile).then(result=>{if(active){setData(result);setError('')}}).catch(reason=>{if(active)setError(reason.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[revision,profile.id])
  const mutate=async(operation,message)=>{setError('');setNotice('');try{await operation();setNotice(message);setRevision(value=>value+1);return true}catch(reason){console.error('[BIEM team]',reason);setError(reason.message);return false}}
  return {data,loading,error,notice,mutate,refresh:()=>setRevision(value=>value+1)}
}

function TeamModal({type,clients,onClose,onSave}){
  const submit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));onSave(values)}
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="team-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><header><div><span>CREAR</span><h2>{type==='task'?'Nueva tarea':type==='deliverable'?'Nuevo entregable':type==='resource'?'Nuevo borrador estratégico':'Nueva nota interna'}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><label>Cliente<select name="client_id" required><option value="">Seleccionar</option>{clients.map(client=><option value={client.id} key={client.id}>{client.brand_name}</option>)}</select></label>{type==='task'?<><label>Título<input name="title" required/></label><label>Tipo<select name="task_type"><option value="strategy">Estrategia</option><option value="design">Diseño</option><option value="video">Video</option><option value="copy">Copy</option><option value="social_media">Social media</option><option value="review">Revisión</option></select></label><label>Fecha límite<input type="date" name="due_date"/></label><label className="wide">Descripción<textarea name="description"/></label></>:type==='deliverable'?<><label>Nombre<input name="name" required/></label><label>Tipo de contenido<input name="content_type" required/></label><label>Fecha límite<input type="date" name="due_date"/></label><label className="wide">Descripción<textarea name="description"/></label></>:type==='resource'?<><label>Título<input name="title" required/></label><label>Tipo<select name="resource_type"><option value="recommendation">Recomendación</option><option value="diagnostic">Diagnóstico</option><option value="growth_route">Ruta de crecimiento</option><option value="next_step">Próximo paso</option></select></label><label className="wide">Contenido<textarea name="content"/></label></>:<><label>Visibilidad<select name="visibility"><option value="admin_and_account_manager">Admin y agente</option><option value="assigned_team">Equipo asignado</option></select></label><label className="wide">Nota<textarea name="note" required/></label></>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="admin-primary" type="submit">Guardar</button></footer></form></div>
}

export default function TeamApp({profile,onSignOut}){
  const meta=roleMeta[profile.role],workspace=useTeamWorkspace(profile),{data}=workspace
  const [active,setActive]=useState('overview'),[menu,setMenu]=useState(false),[modal,setModal]=useState('')
  const clientMap=useMemo(()=>new Map(data.clients.map(client=>[client.id,client])),[data.clients])
  const nav=[['overview','Resumen',LayoutDashboard],['clients','Mis clientes',Users],['tasks','Mis tareas',CheckCircle2],['deliverables','Entregables',Grid2X2],['resources','Materiales',Briefcase],...(profile.role==='account_manager'?[['requests','Solicitudes',MessageCircle],['notes','Notas internas',FileText]]:[])]
  const overdue=data.tasks.filter(task=>task.due_date&&new Date(`${task.due_date}T23:59:59`)<new Date()&&!['completed','paused'].includes(task.status)).length
  const saveModal=async values=>{let ok;if(modal==='task')ok=await workspace.mutate(()=>createTeamTask({...values,status:'pending',priority:'medium',visible_to_account_manager:true,internal_only:true}),'Tarea creada.');else if(modal==='deliverable')ok=await workspace.mutate(()=>createTeamDeliverable({...values,status:'pending',priority:'medium',visible_to_account_manager:true,internal_only:false}),'Entregable creado.');else if(modal==='resource')ok=await workspace.mutate(()=>createTeamResource({...values,status:'draft',visible_to_client:false,visible_to_account_manager:true,internal_only:true}),'Borrador estratégico creado.');else ok=await workspace.mutate(()=>createTeamNote(values),'Nota interna creada.');if(ok)setModal('')}
  const panels={
    overview:<><div className="team-kpis"><article><Users/><span>Clientes asignados</span><strong>{data.clients.length}</strong></article><article><CheckCircle2/><span>Tareas abiertas</span><strong>{data.tasks.filter(t=>!['completed','paused'].includes(t.status)).length}</strong></article><article><Clock3/><span>Próximas fechas</span><strong>{data.tasks.filter(t=>t.due_date).length}</strong></article><article className={overdue?'danger':''}><AlertTriangle/><span>Tareas atrasadas</span><strong>{overdue}</strong></article></div><TeamTaskList tasks={data.tasks.slice(0,6)} clientMap={clientMap} profile={profile} workspace={workspace}/></>,
    clients:<div className="team-client-grid">{data.clients.map(client=><article key={client.id}><div className="team-client-avatar">{initials(client.brand_name)}</div><Badge value={client.status}/><h3>{client.brand_name}</h3><p>{client.name}</p><dl><div><dt>Rol</dt><dd>{roleMeta[client.role_on_client]?.label}</dd></div><div><dt>Renovación</dt><dd>{formatDate(client.renewal_date)}</dd></div>{profile.role==='account_manager'&&<><div><dt>Paquete</dt><dd>{client.package_name||'Sin paquete'}</dd></div><div><dt>Confidencialidad</dt><dd>{client.confidentiality_accepted?'Aceptada':'Pendiente'}</dd></div><div><dt>Onboarding</dt><dd>{client.onboarding_completed?'Completado':client.onboarding_type||'Pendiente'}</dd></div></>}</dl></article>)}</div>,
    tasks:<TeamTaskList tasks={data.tasks} clientMap={clientMap} profile={profile} workspace={workspace}/>,
    deliverables:<div className="team-work-list">{data.deliverables.map(item=><article key={item.id}><div><small>{clientMap.get(item.client_id)?.brand_name||'Cliente'} · {item.content_type}</small><h3>{item.name}</h3><p>{item.description||'Sin descripción'} · {formatDate(item.due_date)}</p><div className="team-drive-links">{(item.drive_assets||[]).filter(asset=>asset.status==='active').map(asset=><span key={asset.id}><a href={asset.drive_url} target="_blank" rel="noopener noreferrer">{asset.name}</a>{asset.visible_to_client&&<small>Visible al cliente</small>}{asset.added_by===profile.id&&<button title="Quitar vínculo" onClick={()=>workspace.mutate(()=>deleteTeamDriveAsset(asset.id),'Vínculo eliminado.')}>×</button>}</span>)}</div></div><div className="team-row-actions"><select value={item.status} onChange={event=>workspace.mutate(()=>updateTeamDeliverable(item.id,{status:event.target.value}), 'Entregable actualizado.')}>{deliverableStatuses[profile.role].map(status=><option value={status} key={status}>{statusLabels[status]||status}</option>)}</select><button onClick={()=>{const name=window.prompt('Nombre del archivo o carpeta');if(!name)return;const drive_url=window.prompt('Pega el enlace de Google Drive o Google Docs');if(!drive_url)return;const visible_to_client=window.confirm('¿Este enlace debe ser visible para el cliente?');workspace.mutate(()=>createTeamDriveAsset(profile,item,{name,drive_url,visible_to_client,asset_type:'file'}),'Archivo de Drive vinculado.')}}>Vincular Google Drive</button></div></article>)}</div>,
    resources:<div className="team-work-list">{data.resources.map(item=><article key={item.id}><div><small>{clientMap.get(item.client_id)?.brand_name||'Cliente'} · {item.resource_type}</small><h3>{item.title}</h3><p>{item.content||'Archivo o material disponible para tu trabajo.'}</p>{item.file_url&&<a href={item.file_url} target="_blank">Abrir material</a>}</div><Badge value={item.status}/></article>)}</div>,
    requests:<div className="team-work-list">{data.requests.map(item=><article key={item.id}><div><small>{clientMap.get(item.client_id)?.brand_name||'Cliente'} · {formatDate(item.created_at)}</small><h3>{item.request_type}</h3><p>{item.description}</p></div><button onClick={()=>workspace.mutate(()=>respondToRequest(item.id,'in_review','Solicitud recibida por el equipo.'),'Solicitud puesta en revisión.')}>Tomar solicitud</button></article>)}</div>,
    notes:<div className="team-work-list">{data.notes.map(item=><article key={item.id}><div><small>{clientMap.get(item.client_id)?.brand_name||'Cliente'} · {formatDate(item.created_at)}</small><p>{item.note}</p></div><span>{item.visibility}</span></article>)}</div>,
  }
  return <div className="team-shell"><aside className={menu?'open':''}><header><strong>biem.</strong><span>EQUIPO</span><button onClick={()=>setMenu(false)}><X/></button></header><div className="team-role-card"><div>{initials(profile.full_name||profile.email)}</div><span><strong>{profile.full_name||profile.email}</strong><small>{meta.label}</small></span></div><nav>{nav.map(([id,label,Icon])=><button className={active===id?'active':''} onClick={()=>{setActive(id);setMenu(false)}} key={id}><Icon size={17}/>{label}</button>)}</nav><button className="team-signout" onClick={onSignOut}><LogOut size={16}/>Cerrar sesión</button></aside><main><header className="team-topbar"><button onClick={()=>setMenu(true)}><Menu/></button><div><small>ESPACIO INTERNO</small><strong>{meta.label}</strong></div><button onClick={workspace.refresh}>Actualizar</button></header><div className="team-page"><div className="team-heading"><div><span>BIEM DIGITAL · OPERACIONES</span><h1>{active==='overview'?`Hola, ${(profile.full_name||'equipo').split(' ')[0]}`:nav.find(item=>item[0]===active)?.[1]}</h1><p>{active==='overview'?meta.intro:'Información limitada a tus clientes y tareas asignadas.'}</p></div>{profile.role==='account_manager'&&['tasks','notes','deliverables','resources'].includes(active)&&<button className="admin-primary" onClick={()=>setModal(active==='tasks'?'task':active==='deliverables'?'deliverable':active==='resources'?'resource':'note')}><Plus size={16}/>Crear {active==='tasks'?'tarea':active==='deliverables'?'entregable':active==='resources'?'borrador':'nota'}</button>}</div>{workspace.loading&&<div className="data-feedback loading">Sincronizando trabajo...</div>}{workspace.error&&<div className="data-feedback error"><AlertTriangle size={16}/>{workspace.error}</div>}{workspace.notice&&<div className="data-feedback success"><CheckCircle2 size={16}/>{workspace.notice}</div>}{panels[active]}</div></main>{menu&&<div className="team-overlay" onClick={()=>setMenu(false)}/>} {modal&&<TeamModal type={modal} clients={data.clients} onClose={()=>setModal('')} onSave={saveModal}/>}</div>
}

function TeamTaskList({tasks,clientMap,profile,workspace}){return <div className="team-work-list">{tasks.map(task=><article key={task.id}><div><small>{clientMap.get(task.client_id)?.brand_name||'Cliente'} · {task.task_type}</small><h3>{task.title}</h3><p>{task.description||'Sin descripción'} · vence {formatDate(task.due_date)}</p>{task.result_url&&<a href={task.result_url} target="_blank">Abrir resultado</a>}</div><div className="team-row-actions"><select value={task.status} onChange={event=>workspace.mutate(()=>updateTeamTask(task.id,{status:event.target.value}), 'Tarea actualizada.')}>{taskStatuses.map(status=><option value={status} key={status}>{statusLabels[status]}</option>)}</select><button onClick={()=>{const url=window.prompt('Enlace del archivo o resultado',task.result_url||'');if(url)workspace.mutate(()=>updateTeamTask(task.id,{result_url:url}),'Resultado guardado.')}}>Subir enlace</button><button onClick={()=>{const comment=window.prompt('Comentario interno',task.internal_comment||'');if(comment!==null)workspace.mutate(()=>updateTeamTask(task.id,{internal_comment:comment}),'Comentario guardado.')}}>Comentar</button></div></article>)}{!tasks.length&&<div className="team-empty"><CheckCircle2 size={28}/><strong>No tienes elementos pendientes</strong><span>Las nuevas asignaciones aparecerán aquí.</span></div>}</div>}
